# NOTE: rename me to "docker-compose.yml" to use the (deprecated) docker-compose up command to start the cluster

networks:
  ndn_compute_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  nfd:
    build: ./cluster/nfd-node
    volumes:
       - ./cluster/nfd-node-config:/custom-config
       - ./sec_data/certs:/certs
    entrypoint: ["/usr/bin/nfd"]
    command: ["--config", "/custom-config/nfd.conf"]
    container_name: nfd1
    networks:
      ndn_compute_net:
        ipv4_address: 192.168.1.2
    environment:
      - APP_PREFIX=ndn-compute
  driver:
    build: 
      context: ./
      dockerfile: ./cluster/driver/Dockerfile
    container_name: driver1
    networks:
      ndn_compute_net:
        ipv4_address: 192.168.1.10
    ports:
      - "5214:5214"
    environment:
      - APP_PREFIX=ndn-compute
      - MANAGEMENT_PORT=5214
    volumes:
      - ./generated_data/distributed/manifest:/app/manifest
  # TODO: docker-compose for loop??
  # TODO: doing it like this generates an image for every instance, even though the instance is identical
  worker1:
    build:
      context: ./
      dockerfile: ./cluster/worker/Dockerfile
    container_name: worker1
    networks:
      ndn_compute_net:
        ipv4_address: 192.168.1.20
    environment:
      - APP_PREFIX=ndn-compute
      - WORKER_ID=1
    volumes:
      - ./generated_data/distributed/1:/app/data
      - ./generated_data/distributed/manifest:/app/manifest
  worker2:
    build:
      context: ./
      dockerfile: ./cluster/worker/Dockerfile
    container_name: worker2
    networks:
      ndn_compute_net:
        ipv4_address: 192.168.1.21
    environment:
      - APP_PREFIX=ndn-compute
      - WORKER_ID=2
    volumes:
      - ./generated_data/distributed/2:/app/data
      - ./generated_data/distributed/manifest:/app/manifest
