networks:
  ndn_compute_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  nfd:
    build: ./nfd-node
    volumes:
       - ./nfd-node-config:/custom-config
    entrypoint: ["/usr/bin/nfd"]
    command: ["--config", "/custom-config/nfd.conf"]
    container_name: nfd1
    networks:
      ndn_compute_net:
        ipv4_address: 192.168.1.2
